[program:sitepulse-queue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/sitepulse/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --queue=default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=8
redirect_stderr=true
stdout_logfile=/var/log/supervisor/sitepulse-queue.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=30
startsecs=3
